### ISSUE TITLE
sideMenu 기능 추가

### ISSUE THREAD

**Issue by LimEunSang** [AI-Homepage-Practice-Frontend/AI-Homepage#1]
## 📒 이슈 내용
> Header.js 내 sideMenu 아이템 클릭 시 열려있는 다른 아이템들 닫히게 하기

## 📑 상세 내용
- 하나의 아이템이 클릭되면 나머지 아이템들은 닫히게 만들기

## ✔️ 체크리스트
- [x] 완성
- [x] 미완성

**Comment by LimEunSang** [comment]
빨리 해결해주세요 현기증나요

**Comment by suinj8** [comment]
위 이슈와 중복으로 닫습니다.
