### ISSUE TITLE
연구분야 페이지 수정 필요

### ISSUE THREAD

**Issue by euny0ung** [AI-Homepage-Practice-Frontend/AI-Homepage#15]
## 이슈 내용
- 연구분야 페이지를 만들었습니다 (_저번주에 했던 것 올립니다)_

## 상세 내용
1. 각 버튼을 누르면 해당 컴포넌트가 뜹니다. 이때 버튼 클릭시 visible 값을 각자 다르게 주고, 삼항 연산자로 해당 visible 값마다 컴포넌트를 다르게 주었는데 좋은 방법이 아닌 것 같아 수정이 필요합니다.
2. 버튼 글자 길이의 차이 때문에 창을 줄이면 버튼 크기가 제각각입니다. 창이 작아지면 버튼 크기도 작아지도록 수정이 필요합니다.
3. 사진이 없으면 밋밋할 것 같은데, 잘못 넣으면 유치한 느낌을 줍니다. 어떤 사진을 넣을지 결정해야합니다.
4. 상단의 연구실 설명은 창을 줄일시 폰트 사이즈가 작아지게 설정하였습니다. 그런데 창을 계속 줄이면 글자가 세로로 정렬됩니다. => divider을 box로 바꾸기
5. 버튼과 회색 박스가 따로 노는 문제

## 체크리스트

- [x] 1번
- [x] 2번
- [x] 3번
- [x] 4번
- [x] 5번

**Comment by LimEunSang** [comment]
은영님이 만든 researcher_field_page 브랜치에 들어가서  실행시키고 이슈 내용 수정해보려고 했는데

![image](https://user-images.githubusercontent.com/86942472/167460513-36515d9d-7cc7-4624-b16c-e88df547a50d.png)

다른 오류는 다 수정했는데  이 오류가 뭔지 모르겠네요..
vscode에서 researcher_field_page브랜치 실행시킬때 저랑 똑같은 오류 뜨시는 분 있나요?

**Comment by LimEunSang** [comment]
추가로 그 브랜치에서 아주 조금 코드 수정했는데 변경내용 push하고 commit 남겨놓을게요.

**Comment by baaaam771** [comment]
확인해보니 저도 동일한 에러 나옵니다

**Comment by baaaam771** [comment]
일단 모듈 설치해주니 에러 문제는 해결됩니다

**Comment by baaaam771** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/60038592/167537083-9766a1db-ad66-4b5e-8fd8-ebfd538074cb.png">

**Comment by suinj8** [comment]
sass 모듈 설치하니까 실행은 되네요.
그런데 저도 범기님같이 화면이 이상하게 나옵니다.
![image](https://user-images.githubusercontent.com/90179555/167576135-a5024a1d-212d-4740-99d6-8fb30ca2138a.png)

**Comment by LimEunSang** [comment]
npm i node-sass
저도 해결했습니다
package json 파일에 의존성 추가하고 다시 commit 해놓을게요

**Comment by LimEunSang** [comment]
2. 각 버튼에 sx 속성에 mediaquery를 적용해 fontsize를 설정할 수 있습니다.
![image](https://user-images.githubusercontent.com/86942472/167590968-8c1323f9-758b-4207-88ca-5bc0b6804a76.png)
이런식으로.

하지만 버튼 내 글자 사이즈의 최소값이 한계가 있기 때문에 창 크기를 최대로 줄이면 여전히 줄바꿈 됩니다.
이 문제를 해결하기 위해 창 크기에 따라 한 줄에 배치되는 버튼의 개수를 조절하는 방법이 가장 나아보입니다.

5. 회색 배경으로 설정해놓은 grid 속성에 marginLeft: "50%" 적용돼있습니다. 이거 삭제하면 해결되는 거 같습니다.
추가적으로 이 속성 때문에 수인이 스크린샷에서 보는바와 같이 이상하게 나옵니다.
![image](https://user-images.githubusercontent.com/86942472/167591723-3fd64aef-1bf3-41d4-8441-3d705bdf030b.png)

**Comment by euny0ung** [comment]
https://codesandbox.io/s/16page-last-rqeod6?file=/src/App.js

코드샌드박스 링크 올립니다.
