### ISSUE TITLE
참여 교수 페이지

### ISSUE THREAD

**Issue by euny0ung** [AI-Homepage-Practice-Frontend/AI-Homepage#20]
## 이슈 내용
- 참여 교수 페이지를 만들었습니다.

## 상세 내용
1. '성명'이라는 글자가 들어가면 어색한 것 같아서 뺐습니다.
2. 이미지 경로 오류가 있습니다.
3. 디자인 변경이 필요하다면 수정할 예정입니다.
4. 페이지를 이동했을 때 헤더, 푸터가 안나옵니다. 제가 뭘 안한것 같은데 혹시 아시는 분은 도와주세요

## 체크리스트

- [x] 1번
- [x] 2번
- [x] 3번
- [x] 4번

**Comment by euny0ung** [comment]
<img width="477" alt="성명전" src="https://user-images.githubusercontent.com/56199780/166969856-64f2fef0-b95f-4509-afe7-cbe508cfd0d3.PNG">
<img width="802" alt="성명후" src="https://user-images.githubusercontent.com/56199780/166969930-7aafc6d8-2262-483c-9d11-854128cede58.PNG">

성명을 썼을 때와 안 썼을 때 비교사진 입니다.

**Comment by baaaam771** [comment]
> <img alt="성명전" width="477" src="https://user-images.githubusercontent.com/56199780/166969856-64f2fef0-b95f-4509-afe7-cbe508cfd0d3.PNG">
> 
> <img alt="성명후" width="802" src="https://user-images.githubusercontent.com/56199780/166969930-7aafc6d8-2262-483c-9d11-854128cede58.PNG">
> 
> 성명을 썼을 때와 안 썼을 때 비교사진 입니다.

성명이라는 명치 표기 없는 아래 방식이 더 보기 좋습니다

**Comment by baaaam771** [comment]
성명이라는 명칭 표기 없는 아래 방식이 더 보기 좋습니다

**Comment by baaaam771** [comment]
[fix : Add header,subheader, footer](https://github.com/AI-Homepage-Practice-Frontend/AI-Homepage/commit/25cc62591e8575de402b4a0d78cfc5114069d7fd) 이와 같은 방식으로 4번 문제 해결했습니다 git pull 해서 확인해보세요
@euny0ung

**Comment by suinj8** [comment]
1. 저도 아래방식이 훨신 이쁜거같습니다. 
2. 이미지 경로 "../../assets/images/jbnu.png"; 이렇게 해보세요
    baby사진이 없어서 jbnu사진으로 제가 해봤고 나오네요!
    추가로 교수사진 부분에 image도 element.img로 수정하셔야 될 것 같습니다.
3. 어떻게 수정하신지를 모르겠어요,, 
4. 범기님이 잘 설명해 주셨지만 한마디 얹으면 모든 페이지를 구성할 때 항상
    header, subheader, footer를 추가해 주어야 합니다.

**Comment by euny0ung** [comment]
두분 다 감사합니다!!

**Comment by euny0ung** [comment]
> 1. 저도 아래방식이 훨신 이쁜거같습니다.
> 2. 이미지 경로 "../../assets/images/jbnu.png"; 이렇게 해보세요
>    baby사진이 없어서 jbnu사진으로 제가 해봤고 나오네요!
>    추가로 교수사진 부분에 image도 element.img로 수정하셔야 될 것 같습니다.
> 3. 어떻게 수정하신지를 모르겠어요,,
> 4. 범기님이 잘 설명해 주셨지만 한마디 얹으면 모든 페이지를 구성할 때 항상
>    header, subheader, footer를 추가해 주어야 합니다.

baby를 넣은줄 알았는데 안들어갔나보네요 감사합니다!! 앗 3번은 제가 나중에 하려고 써둔거예요😅 수정하겠습니다.

**Comment by LimEunSang** [comment]
더미 이미지 넣으실 때 "https://source.unsplash.com/random" 이거 활용해보세요 ~

![image](https://user-images.githubusercontent.com/86942472/167392365-5c62b5b8-1f81-4580-a531-82a61d9ef1ed.png)

이런식으로.

**Comment by euny0ung** [comment]
오 이런것도 있군요 처음 알았어요 감사합니다!!

**Comment by euny0ung** [comment]
![참여교수 완성](https://user-images.githubusercontent.com/56199780/168055739-30c911a9-2b81-41f8-8b0b-546575cd26e8.PNG)
