### ISSUE TITLE
연구분야 페이지 - 버튼 클릭시 화면이 안 나오는 경우

### ISSUE THREAD

**Issue by euny0ung** [AI-Homepage-Practice-Frontend/AI-Homepage#46]
## 📒 이슈 내용
> 버튼을 눌렀을때 화면이 출력 안되는 경우가 있습니다.

## 📑 상세 내용
1. 버튼 클릭시 id가 변경되고, visible===id 이면 컴포넌트를 보여주는 코드에서 useState를 이용하여 클릭한 버튼의 name값에 따라 화면을 바꿔주는 코드로 변경하였습니다.
2. 아래 코드와 같이 console.log(name)을 추가하고 버튼을 계속 눌러 확인해보니, 사진처럼 가끔씩 undefined가 뜹니다.(화면 출력이 안되는 경우)

const buttonValueSetting = (e) => {
const { name } = e.target;
setContents(name); // contents 값을 name으로 변경
console.log(name);
};

## ✔️ 체크리스트
- [x] name이 undefined로 뜨는 이유 확인
- [x] 코드 수정

<img width="195" alt="됐다가안됐다가" src="https://user-images.githubusercontent.com/56199780/170880728-c746feb8-95dd-4cee-9af0-7969e7c030ad.PNG">

**Comment by euny0ung** [comment]
혹시 코드가 길어서 보기 불편하실까봐 문제있는 부분만 따로 올립니다. 

const buttonValueSetting = (e) => {
    const { name } = e.target;
    setContents(name);   // contents 값을 name(engTitle)로 변경
  };


 const selectComponent = { // engTitle 값에 따라 다른 화면 출력
    trans: (
      `<Description
        title={FieldName[0].title}
        subtitle={FieldName[0].subtitle}
        desc={FieldName[0].desc}
        image={imgUrl}
      />`
    ),
    natural: (
      `<Description
        title={FieldName[1].title}
        subtitle={FieldName[1].subtitle}
        desc={FieldName[1].desc}
        image={imgUrl}
      />`
    ),


onClick={buttonValueSetting} //버튼 클릭시 buttonValueSetting 호출
        key={id}
        name={engTitle} // name값은 각 버튼의 영어이름


{contents && selectComponent[contents]} // contents 값에 따른 화면 출력

**Comment by suinj8** [comment]
console.log(e.target); 로 찍어보니까 두가지 경우가 나오네요.

아래 사진과 같이 p태그가 찍히는 경우랑 div태그가 찍히는 경우가 있습니다.
![image](https://user-images.githubusercontent.com/90179555/170985577-058f1c89-9b26-415f-bee4-3ff0ce83937a.png)

버튼의 글씨를 찍으면 p태그가 출력되고 (아래 사진의 노란색 부분)
글씨 외 공간을 찍으면 button태그가 출력됩니다. (그 외 부분)
![image](https://user-images.githubusercontent.com/90179555/170984978-59125d40-0e7c-4feb-baec-41c831bced83.png)

버튼의 글씨컨텐츠를 Typography로 작성을 하셨고
따라서 onclick 실행 시 글씨를 클릭하면 이벤트 파라미터로 버튼이아닌 Typography가 전달되게 됩니다.

이 Typography가 p태그로 바꾸어지고 당연히 p태그 내에는 name속성이 없으니 undefine이 나오게 됩니다.

간단하게 Typography를 없애면 해결될거 같습니다. 글씨는 좀 작아지긴 하지만요...
그 외 방법은 좀더 생각을 해봐야 할것 같네요.

**Comment by suinj8** [comment]
왜 이렇게 작동하는지는 저도 찾아봐야 할거 같습니다.
해결법은 typography를 없애고 버튼 자체에 fontSize를 조정해주면 될거 같네요.

**Comment by LimEunSang** [comment]
정수인 캐리.. 저도 button이 눌릴 때랑 button 속 typography가 눌릴 때에 따라서 다르게 동작할거라고는 상상도 못했네요.

**Comment by euny0ung** [comment]
진짜 감사합니다 😭😭😭 저도 저게 문제인지 생각도 못했네요ㅠ
