### ISSUE TITLE
프로젝트 페이지 - 보여지는 프로젝트 개수 문제

### ISSUE THREAD

**Issue by euny0ung** [AI-Homepage-Practice-Frontend/AI-Homepage#55]
## 📒 이슈 내용
> 프로젝트 페이지에 데이터를 뿌려주는 방식에 있어서 백엔드와 프론트엔드가 생각한 구현 방식이 다른것 같습니다

## 📑 상세 내용
1. 백엔드는 버튼에 분야를 쓰고 버튼을 누르면 해당 분야의 모든 프로젝트를 보여주는 방식으로 알고 있습니다.
2. 프론트엔드는 버튼에 프로젝트 이름을 쓰고 버튼을 누르면 해당 프로젝트의 설명을 보여주는 방식으로 구현했습니다.
3.  해당 페이지의 UI와 mock api는 제가 작업하였고, 서로 생각했던게 달라 코드가 지저분해졌지만 mock api를 문제없이 연결했습니다.
4. 두가지 선택지가 있습니다.  API, UI 수정 없이 그대로 하기 / 의도대로 구현하기 (API나 UI 둘 중 하나를 수정)

## ✔️ 체크리스트
- [ ] 어떻게 할지 결정하기

**Comment by LimEunSang** [comment]
아하하...... 그러네요
해당 페이지 코드 리뷰 할 때 아무런 의심을 못했었네요ㅠ 논문페이지 같이 모든 프로젝트 리스트를 보여주는게 맞는데
저는 의도대로 수정하는게 맞다고 생각합니다..!

**Comment by euny0ung** [comment]
그러면 프로젝트 설명 부분 디자인을 바꿀까요??

**Comment by LimEunSang** [comment]
아 지금 PR 보고왔는데 글 보니까 지금 은영님이 구현한게 딱 서울대네요. 저희가 요구사항이 명확하지 않은 상태에서 서울대 홈페이지를 참고하여 구현중이라면 제 생각에는 확실하게  그대로 하는게 맞는 거 같아요. 죄송합니다. 이랬다저랬다해서..
버튼에 분야를 쓰고 버튼을 누르면 해당 분야의 모든 프로젝트를 보여주는 방식 (x)
버튼에 프로젝트 이름을 쓰고 버튼을 누르면 해당 프로젝트의 설명을 보여주는 방식 (o)

**Comment by LimEunSang** [comment]
어떻게 할지 결정된 후에 은영님이 직접 백앤드와 소통해주시면 감사하겠습니다!

**Comment by baaaam771** [comment]
저도 이부분은 api를 수정하는게 맞다고 생각합니다.
회의 때도 구현하셨던 object 형태로 맞춰주기로 했어서 
```
FieldName = [
      {
        id: 0,
        engTitle: "trans",
        title: "기계번역",
        participants: "기계번역의 부제목..",
        desc: "인간이 사용하는 자연 언어를 컴퓨터를 사용하여 다른 언어로 번역한다.{' '} 최근 딥러닝 알고리즘을 통해 수준 높은 기계번역을 할 수 있게 되었다. 연구실에서 무슨 프로젝트를 어떻게 하고있고 어쩌구",
      },
     {
        id: 1,
        engTitle: "qaa",
        title: "질의응답",
        participants: "질의응답의 부제목..",
        desc: "사용자의 질의에 대한 답변이 될 수 있는 정답을 문서 집합내에서 탐색하여 사용자에게 제시해주는 시스템이다. 일반적으로 질의응답 시스템은 사용자의 질의에 관련된 문서를 검색하는 후보검색 단계 (candidate retrieval phase) 와 검색된 문서 내에서 정답을 생성하는 정답추출 단계 (answer extraction phase) 로 구성된다. 연구실에서 무슨 프로젝트를 어떻게 하고있고 어쩌구",
      },
       ...
]
```
이거 형태 유지하셔도 될것 같아요

**Comment by suinj8** [comment]
저도 윗분들 생각과 같습니다.
