### ISSUE TITLE
Admin 메뉴트리 구성

### ISSUE THREAD

**Issue by baaaam771** [AI-Homepage-Practice-Frontend/AI-Homepage#58]
## 📒 이슈내용
> Admin 메뉴트리 구성 변경 필요
> code naming이나 구조적으로 user 관련 코드와 admin 관련 코드를 분리시킬 필요가 있음

## 📑 상세 내용
1. admin 관련 component, pages 분리 
2. admin 관련 code 이름 수정

## ✔️ 체크리스트
- [ ] admin 관련 component, pages 분리 
- [ ] admin 관련 code 이름 수정

**Comment by suinj8** [comment]
이슈에 대해 자세히 설명해 주실 수 있을까요?
이해를 잘 못했습니다.

**Comment by baaaam771** [comment]
<img width="178" alt="image" src="https://user-images.githubusercontent.com/60038592/174950697-f29c79df-ed31-4c98-8003-c2ba6e07f177.png">
저희 메뉴 구성이 이런식으로 되어 있는데
사용자 페이지와 충동하지 않게 하기 위해서
<img width="178" alt="image" src="https://user-images.githubusercontent.com/60038592/174951062-177b25ce-d48c-4d61-8e53-a3be2e8fbd33.png">
이런식으로 admin 폴더를 따로 만들어서
여기에 관리자페이지 관련 코드들을 모으는게 어떤지 의견 물어본거에요!

**Comment by suinj8** [comment]
아 저는 좋은 생각인거 같습니다.
잠깐 브랜치 넘어가서 살펴봤는데 그렇게 따로 관리하는게
좋겠더라구요.

**Comment by euny0ung** [comment]
저도 그렇게 하는게 좋을것같다고 생각합니다.
"admin 관련 code 이름 수정" 이 부분은 user 코드를 admin에서 재활용할 때 변수, 함수 이름을 바꾼다는 의미인가요?? 이해를 못해서 예시를 들어주시면 감사하겠습니다!

**Comment by baaaam771** [comment]
> 저도 그렇게 하는게 좋을것같다고 생각합니다. "admin 관련 code 이름 수정" 이 부분은 user 코드를 admin에서 재활용할 때 변수, 함수 이름을 바꾼다는 의미인가요?? 이해를 못해서 예시를 들어주시면 감사하겠습니다!

이부분을 처음 작성했을 때는
1. user와 admin 폴더 분리
2. user와 admin 폴더 통합
둘 중에 하나를 선택하고 난 이후의 과정을 생각한건데요


2번을 선택하게 된다면
하나의 같은 폴더를 공유해서 파일 이름을 
```
infoChannel.js 
AdminInfoChannel.js
```
이런식으로 구분을 해주고


1번을 선택하게 된다면
이름은 infoChannel.js 똑같이 사용하더라도 
```
admin/pages/news/InfoChannel
pages/news/InfoChannel
```
이런식으로 속해있는 폴더가 다르기 때문에
AdminInfoChannel.js와 같이 길게 이름을 쓰지 않고 
하나로 통일하려고 제안한 내용입니다

**Comment by LimEunSang** [comment]
동의합니다. 또한  이름 통일에 대한 이점 외에도 파일 관리 측면에서 admin 폴더를 만들어 관리하는 것이 더 효율적이라는 생각입니다.
