### ISSUE TITLE
소식 - 소식통, 언론보도 클릭 시 언론보도 자세히 보기 페이지로만 이동하는 오류

### ISSUE THREAD

**Issue by LimEunSang** [AI-Homepage-Practice-Frontend/AI-Homepage#60]
FeaturedPost 컴포넌트 내 onClick 이벤트로 언론보도 자세히 보기 페이지로 이동하게 코드를 작성하여 소식통 Post를 클릭해도 언론보도 자세히 보기 페이지로 이동함.
FeaturedPost를 호출하는 상위 컴포넌트 내에서 onClick 함수를 props로 전달하여 각 Post에 맞게 자세히 보기 페이지로 이동하도록 수정하여야함.

**Comment by baaaam771** [comment]
어디 브랜치에서 발생하고 있나요?

**Comment by LimEunSang** [comment]
> 어디 브랜치에서 발생하고 있나요?

댓글 확인을 너무 늦게 했네요.. 
제가 코드 작성한 자세히 보기 페이지 구현에서 발생하는 오류인데, 코드를 최대한 줄이려고 하다보니까 실수로 잘못 작성한 부분이네요. 현재 범기님 PR까지 merge 하면 그때 브랜치 파서 작성하겠습니다. 제가 금방 해결할 수 있어요!
