### ISSUE TITLE
프로젝트 페이지 디자인 수정

### ISSUE THREAD

**Issue by euny0ung** [AI-Homepage-Practice-Frontend/AI-Homepage#62]
## 📒 이슈 내용
> 프로젝트 페이지 디자인을 수정해야합니다.

## 📑 상세 내용
1. 백엔드에서 api 수정하기 어렵다고 하여 프로젝트 페이지의 디자인을 바꿔야할것 같습니다.
2. 디자인에 대해 좋은 아이디어 있으면 말씀해주세요. 일단 저는 mui 아코디언을 이용해서 다음과 같이 구현해볼까 생각하고 있습니다.

## ✔️ 체크리스트
- [ ] 디자인 정하기 
- [ ] 페이지 수정하기

![image](https://user-images.githubusercontent.com/56199780/175811176-8f98e11d-f2ea-4c56-a390-7685b58459e3.png)

**Comment by LimEunSang** [comment]
아코디언 나쁘지 않네요~ content에 사진같은것도 있고 내용이 장황하면 자세히 보기 페이지를 따로 구현하는게 더 낫겠지만 그게 아니니까 위 방식이 적절해보입니다.
아까 상의한 내용대로 참여자를 밑으로 내리고 그 자리에 descriptioin을 넣으면 완벽할 거 같네요.

**Comment by baaaam771** [comment]
![image](https://user-images.githubusercontent.com/60038592/175907112-bac31cda-c9dc-482e-be8c-9f97304146a9.png)
현재 사용자 페이지 API가  다음과 같이 정해졌고
 
기존에 만들었던 연구분야 프론트에서 데이터를 입력받는 형식이
![image](https://user-images.githubusercontent.com/60038592/175907178-fa4a3bc0-a167-41d4-b68d-800ef56fc98c.png)
형태이기 때문에 
db의 title은 프론트의 title에
description부분을 subtitle에 
contents 부분을 desc에 넣어 동적으로 관리하고
빠져있는 participant만 맨아래에 추가하여 출력해주는 것도 방법일것 같습니다

예시로 서울대 페이지도 기존에 만들어진 tab 방식에서 참여자만 맨 아래에 추가된 방식입니다
![image](https://user-images.githubusercontent.com/60038592/175908031-90e36bed-b5ed-4e25-8859-cdc519c31344.png)
https://aiis.snu.ac.kr/sub1_3_1.php

이 방식을 활용하게 되면 변경사항은

```
const FieldName = [
  {
    id: 0,
    engTitle: "trans",
    title: "기계번역",
    subtitle: "기계번역의 부제목..",
    desc: "인간이 사용하는 자연 언어를 컴퓨터를 사용하여 다른 언어로 번역한다.{' '} 최근 딥러닝 알고리즘을 통해 수준 높은 기 
   계번역을 할 수 있게 되었다. 연구실에서 무슨 프로젝트를 어떻게 하고있고 어쩌구",
   participants: "고언숙 · 곽노준 · 김현진 · 박종우 · 송현오 · 심형보 · 안우영 · 오성주 · 우충완 · 이교구 · 이영기"
  },
...
```
이와 같은 형식으로 participants 만 추가해주고
participants 디자인만 조금 해주면 되어서 시간도 단축될 것 같습니다

**Comment by euny0ung** [comment]
> ![image](https://user-images.githubusercontent.com/60038592/175907112-bac31cda-c9dc-482e-be8c-9f97304146a9.png) 현재 사용자 페이지 API가 다음과 같이 정해졌고
> 
> 기존에 만들었던 연구분야 프론트에서 데이터를 입력받는 형식이 ![image](https://user-images.githubusercontent.com/60038592/175907178-fa4a3bc0-a167-41d4-b68d-800ef56fc98c.png) 형태이기 때문에 db의 title은 프론트의 title에 description부분을 subtitle에 contents 부분을 desc에 넣어 동적으로 관리하고 빠져있는 participant만 맨아래에 추가하여 출력해주는 것도 방법일것 같습니다
> 
> 예시로 서울대 페이지도 기존에 만들어진 tab 방식에서 참여자만 맨 아래에 추가된 방식입니다 ![image](https://user-images.githubusercontent.com/60038592/175908031-90e36bed-b5ed-4e25-8859-cdc519c31344.png) https://aiis.snu.ac.kr/sub1_3_1.php
> 
> 이 방식을 활용하게 되면 변경사항은
> 
> ```
> const FieldName = [
>   {
>     id: 0,
>     engTitle: "trans",
>     title: "기계번역",
>     subtitle: "기계번역의 부제목..",
>     desc: "인간이 사용하는 자연 언어를 컴퓨터를 사용하여 다른 언어로 번역한다.{' '} 최근 딥러닝 알고리즘을 통해 수준 높은 기 
>    계번역을 할 수 있게 되었다. 연구실에서 무슨 프로젝트를 어떻게 하고있고 어쩌구",
>    participants: "고언숙 · 곽노준 · 김현진 · 박종우 · 송현오 · 심형보 · 안우영 · 오성주 · 우충완 · 이교구 · 이영기"
>   },
> ...
> ```
> 
> 이와 같은 형식으로 participants 만 추가해주고 participants 디자인만 조금 해주면 되어서 시간도 단축될 것 같습니다

자세한 피드백 감사합니다! 범기님은 기존 디자인 그대로 하는게 낫다고 생각하시는거 맞나요??

**Comment by suinj8** [comment]
프로젝트의 설명의 길이에 따라 아코디언을 쓰는게 좋을수도 기존의 방식을 고수하는게 좋을수도 있을거 같아요.
텍스트가 길지 않다면 아코디언이 더 깔끔해 보일수 있겠다 라고 생각하지만
내용이 길어진다면 너무 긴 내용이 아코디언으로 보여지면 좋은 경험은 아닐거 같습니다.

내용을 길다, 짧다가 확실히 정해지면 추후 정해도 되지 않을까 생각합니다.

결론은 일단은 구현을 해놓았고 범기님 말씀대로 약간의 수정만 하면 되는 기존의 방식에서 
약간만 수정하는게 구현하시는 입장에서도 편하지 않을까 생각됩니다.

**Comment by euny0ung** [comment]
일단 기존 디자인으로 구현해보고 또 이슈 남기겠습니다!
