### ISSUE TITLE
Admin Member API와 UI의 다름으로 인해 UI 수정 필요할지 논의

### ISSUE THREAD

**Issue by suinj8** [AI-Homepage-Practice-Frontend/AI-Homepage#79]
## 📒 이슈 내용
> API 시나리오에서는 직책(position)이 따로 빠져있어서 각 객체별로 직책 값을 가지고 있지 않습니다.
반면 UI에서는 각 멤버 별 직책을 보여줍니다. 
따라서 현재 구현은 ValueFormatter를 이용하여 일괄적으로 교수나 연구원을 집어넣어 주었습니다.
API변경은 번거로우니 UI적으로 수정을 할지 말지 의견을 말씀해주세요.

## 📑 상세 내용
1. 의견을 댓글로 말씀해주세요.
a. 지금처럼 변경없이 ValueFormatter를 이용하여 일괄 처리한다.
b. 굳이 교수를 눌러서 창에 들어왔는데 어차피 값들은 모두  교수이다.  따로 보여줄 필요가 있을까? 직책 컬럼을 삭제하자!

## ✔️ 체크리스트
- [ ] 의견종합완료

**Comment by LimEunSang** [comment]
b!
현재 디자인은 변경 이전에 고안된 디자인이기 때문에  지금은 불필요합니다.
